### ISSUE TITLE
Not launching on Mac, not finding libOpenColorIO?

### ISSUE THREAD

**Issue by Hammers69** [gugenstudio/xComp#1]
Hi, I just downloaded xComp to have a look, but it seems to not be finding the OpenColor library. Here's my terminal output, would love to know how to proceed. I'm on Mac OS 12.6.1 Many thanks!
```
/Applications/xcomp/bin/xcomp ; exit;
dyld[958]: Library not loaded: '@rpath/libOpenColorIO.2.2.dylib'
  Referenced from: '/Applications/xcomp/bin/xcomp'
  Reason: tried: '/Users/davide/dev/repos/xComp/externals/local/ocio/_build/Release/src/OpenColorIO/libOpenColorIO.2.2.dylib' (no such file), '/Users/davide/dev/repos/xComp/externals/local/ocio/_build/Release/src/OpenColorIO/libOpenColorIO.2.2.dylib' (no such file), '/usr/lib/libOpenColorIO.2.2.dylib' (no such file)
zsh: abort      /Applications/xcomp/bin/xcomp

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

**Comment by dpasca** [comment]
From the terminal, please, launch the application as `/Applications/xcomp/xcomp.command` or double-click on `xcomp.command` from the Finder.

That should fix it.

**Comment by Hammers69** [comment]
Ah thanks so much. Sorry I missed the obvious there :)

**Comment by dpasca** [comment]
> Ah thanks so much. Sorry I missed the obvious there :)

It's good feedback. We should probably put it in the docs. It's not so strange to expect a binary executable to just run 8)
